package cn.com.xbed.app.bean;
// Generated 2015-7-16 16:56:42 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * SvSysParam generated by hbm2java
 */
public class SvSysParam implements java.io.Serializable {

	private Integer sysParamId;
	private String paramKey;
	private String paramValue;
	private String paramTitle;
	private String paramDesc;
	private Date createDtm;

	public Integer getSysParamId() {
		return sysParamId;
	}

	public void setSysParamId(Integer sysParamId) {
		this.sysParamId = sysParamId;
	}

	public String getParamKey() {
		return paramKey;
	}

	public void setParamKey(String paramKey) {
		this.paramKey = paramKey;
	}

	public String getParamValue() {
		return paramValue;
	}

	public void setParamValue(String paramValue) {
		this.paramValue = paramValue;
	}

	public String getParamTitle() {
		return paramTitle;
	}

	public void setParamTitle(String paramTitle) {
		this.paramTitle = paramTitle;
	}

	public String getParamDesc() {
		return paramDesc;
	}

	public void setParamDesc(String paramDesc) {
		this.paramDesc = paramDesc;
	}

	public Date getCreateDtm() {
		return createDtm;
	}

	public void setCreateDtm(Date createDtm) {
		this.createDtm = createDtm;
	}

	@Override
	public String toString() {
		return "SvSysParam [sysParamId=" + sysParamId + ", paramKey=" + paramKey + ", paramValue=" + paramValue + ", paramTitle=" + paramTitle
				+ ", paramDesc=" + paramDesc + ", createDtm=" + createDtm + "]";
	}

}
