package cn.com.xbed.app.bean;
// Generated 2015-8-17 17:50:21 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * XbOrder generated by hbm2java
 */
public class XbOrder implements java.io.Serializable {

	private Integer orderId;
	private Integer stat;
	private Integer lodgerId;
	private String roomId;
	private Integer roomCount;
	private String orderNo;
	private String roomPrice;
	private Integer totalPrice;// 实付价格
	private Integer discountPrice;// 优惠多少钱
	private String currency;
	private Date arrivalTime;
	private Date departTime;
	private Integer nightCount;
	private Integer source;
	private String subSource;
	private Date createTime;
	private Date expireTime;
	private String remark;
	private Integer payType;
	private Date payDtm;
	private String otaOrderNo;
	private Integer invoiceRecId;
	private Integer orderType;
	private String exHold1;
	private String exHold2;
	private String exHold3;
	private String lodgerName;
	private String lodgerMobile;
	private String parentOrderNo;
	private String childOrderNo;
	private Date lastModDtm;

	public Integer getDiscountPrice() {
		return discountPrice;
	}

	public void setDiscountPrice(Integer discountPrice) {
		this.discountPrice = discountPrice;
	}

	public Date getPayDtm() {
		return payDtm;
	}

	public void setPayDtm(Date payDtm) {
		this.payDtm = payDtm;
	}

	public Date getLastModDtm() {
		return lastModDtm;
	}

	public void setLastModDtm(Date lastModDtm) {
		this.lastModDtm = lastModDtm;
	}

	public String getChildOrderNo() {
		return childOrderNo;
	}

	public void setChildOrderNo(String childOrderNo) {
		this.childOrderNo = childOrderNo;
	}

	public String getParentOrderNo() {
		return parentOrderNo;
	}

	public void setParentOrderNo(String parentOrderNo) {
		this.parentOrderNo = parentOrderNo;
	}

	public String getLodgerName() {
		return lodgerName;
	}

	public void setLodgerName(String lodgerName) {
		this.lodgerName = lodgerName;
	}

	public String getLodgerMobile() {
		return lodgerMobile;
	}

	public void setLodgerMobile(String lodgerMobile) {
		this.lodgerMobile = lodgerMobile;
	}

	public Integer getOrderType() {
		return orderType;
	}

	public void setOrderType(Integer orderType) {
		this.orderType = orderType;
	}

	public String getExHold1() {
		return exHold1;
	}

	public void setExHold1(String exHold1) {
		this.exHold1 = exHold1;
	}

	public String getExHold2() {
		return exHold2;
	}

	public void setExHold2(String exHold2) {
		this.exHold2 = exHold2;
	}

	public String getExHold3() {
		return exHold3;
	}

	public void setExHold3(String exHold3) {
		this.exHold3 = exHold3;
	}

	public Integer getInvoiceRecId() {
		return invoiceRecId;
	}

	public void setInvoiceRecId(Integer invoiceRecId) {
		this.invoiceRecId = invoiceRecId;
	}

	public String getOtaOrderNo() {
		return otaOrderNo;
	}

	public void setOtaOrderNo(String otaOrderNo) {
		this.otaOrderNo = otaOrderNo;
	}

	public String getOrderNo() {
		return orderNo;
	}

	public void setOrderNo(String orderNo) {
		this.orderNo = orderNo;
	}

	public Integer getPayType() {
		return payType;
	}

	public void setPayType(Integer payType) {
		this.payType = payType;
	}

	public Integer getOrderId() {
		return orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	public Integer getStat() {
		return stat;
	}

	public void setStat(Integer stat) {
		this.stat = stat;
	}

	public Integer getLodgerId() {
		return lodgerId;
	}

	public void setLodgerId(Integer lodgerId) {
		this.lodgerId = lodgerId;
	}

	public String getRoomId() {
		return roomId;
	}

	public void setRoomId(String roomId) {
		this.roomId = roomId;
	}

	public Integer getRoomCount() {
		return roomCount;
	}

	public void setRoomCount(Integer roomCount) {
		this.roomCount = roomCount;
	}

	public String getRoomPrice() {
		return roomPrice;
	}

	public void setRoomPrice(String roomPrice) {
		this.roomPrice = roomPrice;
	}

	public Integer getTotalPrice() {
		return totalPrice;
	}

	public void setTotalPrice(Integer totalPrice) {
		this.totalPrice = totalPrice;
	}

	public String getCurrency() {
		return currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	public Date getExpireTime() {
		return expireTime;
	}

	public void setExpireTime(Date expireTime) {
		this.expireTime = expireTime;
	}

	public Date getArrivalTime() {
		return arrivalTime;
	}

	public void setArrivalTime(Date arrivalTime) {
		this.arrivalTime = arrivalTime;
	}

	public Date getDepartTime() {
		return departTime;
	}

	public void setDepartTime(Date departTime) {
		this.departTime = departTime;
	}

	public Integer getNightCount() {
		return nightCount;
	}

	public void setNightCount(Integer nightCount) {
		this.nightCount = nightCount;
	}

	public Integer getSource() {
		return source;
	}

	public void setSource(Integer source) {
		this.source = source;
	}

	public String getSubSource() {
		return subSource;
	}

	public void setSubSource(String subSource) {
		this.subSource = subSource;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Override
	public String toString() {
		return "XbOrder [orderId=" + orderId + ", stat=" + stat + ", lodgerId=" + lodgerId + ", roomId=" + roomId + ", roomCount=" + roomCount
				+ ", orderNo=" + orderNo + ", roomPrice=" + roomPrice + ", totalPrice=" + totalPrice + ", currency=" + currency + ", arrivalTime="
				+ arrivalTime + ", departTime=" + departTime + ", nightCount=" + nightCount + ", source=" + source + ", subSource=" + subSource
				+ ", createTime=" + createTime + ", expireTime=" + expireTime + ", remark=" + remark + ", payType=" + payType + ", otaOrderNo="
				+ otaOrderNo + "]";
	}

}
